CREATE TABLE members (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    attribution VARCHAR(30)  NOT NULL
);

CREATE TABLE projects (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              VARCHAR(255)   NOT NULL,
    start_date        DATE           NOT NULL,
    expected_end_date DATE           NOT NULL,
    actual_end_date   DATE,
    total_budget      NUMERIC(19, 2) NOT NULL,
    description       VARCHAR(2000),
    manager_id        BIGINT         NOT NULL,
    status            VARCHAR(30)    NOT NULL
);

CREATE TABLE project_members (
    project_id BIGINT NOT NULL,
    member_id  BIGINT NOT NULL,
    PRIMARY KEY (project_id, member_id),
    CONSTRAINT fk_project_members_project FOREIGN KEY (project_id) REFERENCES projects (id) ON DELETE CASCADE
);

CREATE INDEX idx_projects_status ON projects (status);
CREATE INDEX idx_projects_manager ON projects (manager_id);
CREATE INDEX idx_project_members_member ON project_members (member_id);
